import React from "react";
import IMAGES from "../../Images/Images";

const stadiums = [
  {
    name: "Barzayyakan",
    location: "Location 1",
    image: IMAGES.Image1,
    capacity: "50,000",
  },
  {
    name: "Stadium 2",
    location: "Location 2",
    image: IMAGES.Image2,
    capacity: "60,000",
  },
  {
    name: "Barzayyakan",
    location: "Location 1",
    image: IMAGES.Image1,
    capacity: "50,000",
  },
  {
    name: "Stadium 2",
    location: "Location 2",
    image: IMAGES.Image2,
    capacity: "60,000",
  },
  // Add more stadium objects as needed
];

const Recomendations = () => {
  return (
    <div className="p-4 bg-gray-800 h-[80vh]	flex flex-col justify-center m-8 rounded-3xl mt-20">
      <h1 className="text-4xl mb-4">Recommended Stadiums for You</h1>
      <p className="m-4 ml-16 mb-2"> Generated by Artifical Inteligence</p>
      <div className="flex justify-center items-center gap-6">
        {stadiums.map((stadium, index) => (
          <div
            key={index}
            className="bg-white shadow-2xl shadow-gray-500 overflow-hidden w-[300px] rounded-3xl hover:scale-105 duration-75 hover:outline-green-700 border-2 p-2"
          >
            <img
              src={stadium.image}
              alt={stadium.name}
              className="w-full h-64 object-cover rounded-3xl"
            />
            <div className="p-4">
              <h2 className="text-xl text-black font-bold">{stadium.name}</h2>
              <p className="text-gray-600">{stadium.location}</p>
              <p className="mt-2 text-gray-800">Capacity: {stadium.capacity}</p>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Recomendations;
